# Generated by Django 2.2.2 on 2019-06-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_entrada', models.CharField(max_length=50)),
                ('h_salida', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=50)),
                ('f_digital', models.CharField(max_length=50)),
                ('observa', models.CharField(max_length=50)),
            ],
        ),
    ]
