# Generated by Django 2.2.2 on 2019-06-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0002_auto_20190603_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='h_entrada',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='horario',
            name='h_salida',
            field=models.CharField(max_length=50),
        ),
    ]
