# Generated by Django 2.2.2 on 2019-06-04 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0003_auto_20190603_2208'),
        ('Docente', '0004_horario_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='idcurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso'),
            preserve_default=False,
        ),
    ]
