# Generated by Django 2.2.2 on 2019-06-04 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0003_auto_20190603_2208'),
        ('Docente', '0005_horario_idcurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
            ],
        ),
    ]
