# Generated by Django 2.2.2 on 2019-06-04 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0006_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
