# Generated by Django 2.2.2 on 2019-06-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0008_horario_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='date_time',
            new_name='date_time_entrada',
        ),
        migrations.AddField(
            model_name='horario',
            name='date_time_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
