# Generated by Django 2.2.2 on 2019-06-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0010_horaentrada_horasalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaentrada',
            name='h_entrada',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='horasalida',
            name='h_salida',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
