# Generated by Django 2.2.2 on 2019-06-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0011_auto_20190606_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaentrada',
            name='cod_entrada',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horasalida',
            name='cod_salida',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horaentrada',
            name='h_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horasalida',
            name='h_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
