# Generated by Django 2.2.2 on 2019-06-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0013_horaentrada_f_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaentrada',
            name='f_entrada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
