# Generated by Django 2.2.2 on 2019-06-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0014_auto_20190607_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaentrada',
            name='h_entrada_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
