# Generated by Django 2.2.2 on 2019-06-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0015_horaentrada_h_entrada_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasalida',
            name='f_salida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horasalida',
            name='h_salida_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
