# Generated by Django 2.2.2 on 2019-06-07 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0016_auto_20190607_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horasalida',
            name='idcurso',
        ),
        migrations.RemoveField(
            model_name='horasalida',
            name='iduser',
        ),
        migrations.AddField(
            model_name='horasalida',
            name='id_hora_salida',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Docente.HoraEntrada'),
            preserve_default=False,
        ),
    ]
