# Generated by Django 2.2.2 on 2019-06-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0017_auto_20190607_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horasalida',
            old_name='id_hora_salida',
            new_name='id_hora_entrada',
        ),
    ]
