# Generated by Django 2.2.2 on 2019-06-09 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0004_auto_20190604_0036'),
        ('Docente', '0018_auto_20190607_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='idcurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso'),
            preserve_default=False,
        ),
    ]
