# Generated by Django 2.2.2 on 2019-06-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0019_categoria_idcurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='date_time_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='date_time_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
