# Generated by Django 2.2.2 on 2019-06-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0022_auto_20190609_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='f_digital',
            field=models.CharField(max_length=50),
        ),
    ]
