# Generated by Django 2.2.2 on 2019-06-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='ciclo',
            field=models.CharField(max_length=4),
        ),
    ]
