# Generated by Django 2.2.2 on 2019-06-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0002_auto_20190603_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='idsuer',
            new_name='iduser',
        ),
    ]
